package com.proj;
// Generated 19/06/2014 22:10:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cidade generated by hbm2java
 */
public class Cidade  implements java.io.Serializable {


     private int codCidade;
     private String nomeCidade;
     private String codIbge;
     private String cepPadrao;
     private Set pessoas = new HashSet(0);

    public Cidade() {
    }

	
    public Cidade(int codCidade, String nomeCidade, String codIbge) {
        this.codCidade = codCidade;
        this.nomeCidade = nomeCidade;
        this.codIbge = codIbge;
    }
    public Cidade(int codCidade, String nomeCidade, String codIbge, String cepPadrao, Set pessoas) {
       this.codCidade = codCidade;
       this.nomeCidade = nomeCidade;
       this.codIbge = codIbge;
       this.cepPadrao = cepPadrao;
       this.pessoas = pessoas;
    }
   
    public int getCodCidade() {
        return this.codCidade;
    }
    
    public void setCodCidade(int codCidade) {
        this.codCidade = codCidade;
    }
    public String getNomeCidade() {
        return this.nomeCidade;
    }
    
    public void setNomeCidade(String nomeCidade) {
        this.nomeCidade = nomeCidade;
    }
    public String getCodIbge() {
        return this.codIbge;
    }
    
    public void setCodIbge(String codIbge) {
        this.codIbge = codIbge;
    }
    public String getCepPadrao() {
        return this.cepPadrao;
    }
    
    public void setCepPadrao(String cepPadrao) {
        this.cepPadrao = cepPadrao;
    }
    public Set getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set pessoas) {
        this.pessoas = pessoas;
    }




}


