package com.proj;
// Generated 19/06/2014 22:10:45 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int codPessoa;
     private Pessoa pessoa;
     private BigDecimal rendaMensal;
     private String flgSituacaocarteira;
     private String cnh;
     private String categoria;
     private Set vendas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int codPessoa, Pessoa pessoa, String flgSituacaocarteira, String cnh, String categoria) {
        this.codPessoa = codPessoa;
        this.pessoa = pessoa;
        this.flgSituacaocarteira = flgSituacaocarteira;
        this.cnh = cnh;
        this.categoria = categoria;
    }
    public Cliente(int codPessoa, Pessoa pessoa, BigDecimal rendaMensal, String flgSituacaocarteira, String cnh, String categoria, Set vendas) {
       this.codPessoa = codPessoa;
       this.pessoa = pessoa;
       this.rendaMensal = rendaMensal;
       this.flgSituacaocarteira = flgSituacaocarteira;
       this.cnh = cnh;
       this.categoria = categoria;
       this.vendas = vendas;
    }
   
    public int getCodPessoa() {
        return this.codPessoa;
    }
    
    public void setCodPessoa(int codPessoa) {
        this.codPessoa = codPessoa;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public BigDecimal getRendaMensal() {
        return this.rendaMensal;
    }
    
    public void setRendaMensal(BigDecimal rendaMensal) {
        this.rendaMensal = rendaMensal;
    }
    public String getFlgSituacaocarteira() {
        return this.flgSituacaocarteira;
    }
    
    public void setFlgSituacaocarteira(String flgSituacaocarteira) {
        this.flgSituacaocarteira = flgSituacaocarteira;
    }
    public String getCnh() {
        return this.cnh;
    }
    
    public void setCnh(String cnh) {
        this.cnh = cnh;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


