package com.proj;
// Generated 19/06/2014 22:10:45 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Comissao generated by hbm2java
 */
public class Comissao  implements java.io.Serializable {


     private ComissaoId id;
     private PagamentoVenda pagamentoVenda;
     private Funcionario funcionario;
     private Date dtVenda;
     private Date valComissao;

    public Comissao() {
    }

    public Comissao(ComissaoId id, PagamentoVenda pagamentoVenda, Funcionario funcionario, Date dtVenda, Date valComissao) {
       this.id = id;
       this.pagamentoVenda = pagamentoVenda;
       this.funcionario = funcionario;
       this.dtVenda = dtVenda;
       this.valComissao = valComissao;
    }
   
    public ComissaoId getId() {
        return this.id;
    }
    
    public void setId(ComissaoId id) {
        this.id = id;
    }
    public PagamentoVenda getPagamentoVenda() {
        return this.pagamentoVenda;
    }
    
    public void setPagamentoVenda(PagamentoVenda pagamentoVenda) {
        this.pagamentoVenda = pagamentoVenda;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Date getDtVenda() {
        return this.dtVenda;
    }
    
    public void setDtVenda(Date dtVenda) {
        this.dtVenda = dtVenda;
    }
    public Date getValComissao() {
        return this.valComissao;
    }
    
    public void setValComissao(Date valComissao) {
        this.valComissao = valComissao;
    }




}


