package com.proj;
// Generated 19/06/2014 22:10:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CondicaoPagamento generated by hbm2java
 */
public class CondicaoPagamento  implements java.io.Serializable {


     private int codCondicao;
     private String tipoPagamento;
     private String condicao;
     private Set vendas = new HashSet(0);

    public CondicaoPagamento() {
    }

	
    public CondicaoPagamento(int codCondicao, String tipoPagamento, String condicao) {
        this.codCondicao = codCondicao;
        this.tipoPagamento = tipoPagamento;
        this.condicao = condicao;
    }
    public CondicaoPagamento(int codCondicao, String tipoPagamento, String condicao, Set vendas) {
       this.codCondicao = codCondicao;
       this.tipoPagamento = tipoPagamento;
       this.condicao = condicao;
       this.vendas = vendas;
    }
   
    public int getCodCondicao() {
        return this.codCondicao;
    }
    
    public void setCodCondicao(int codCondicao) {
        this.codCondicao = codCondicao;
    }
    public String getTipoPagamento() {
        return this.tipoPagamento;
    }
    
    public void setTipoPagamento(String tipoPagamento) {
        this.tipoPagamento = tipoPagamento;
    }
    public String getCondicao() {
        return this.condicao;
    }
    
    public void setCondicao(String condicao) {
        this.condicao = condicao;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


