package com.proj;
// Generated 19/06/2014 22:10:45 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PagamentoVenda generated by hbm2java
 */
public class PagamentoVenda  implements java.io.Serializable {


     private PagamentoVendaId id;
     private BigDecimal vlrTotal;
     private BigDecimal vlrJuros;
     private BigDecimal vlrDesconto;
     private BigDecimal vlrMulta;
     private Date dtInipagamento;
     private Date dtFimPagamento;
     private Date dtRegistro;
     private Integer numParcela;
     private BigDecimal vlrPago;
     private Date dtParcela;
     private Set comissaos = new HashSet(0);

    public PagamentoVenda() {
    }

	
    public PagamentoVenda(PagamentoVendaId id, Date dtInipagamento, Date dtRegistro) {
        this.id = id;
        this.dtInipagamento = dtInipagamento;
        this.dtRegistro = dtRegistro;
    }
    public PagamentoVenda(PagamentoVendaId id, BigDecimal vlrTotal, BigDecimal vlrJuros, BigDecimal vlrDesconto, BigDecimal vlrMulta, Date dtInipagamento, Date dtFimPagamento, Date dtRegistro, Integer numParcela, BigDecimal vlrPago, Date dtParcela, Set comissaos) {
       this.id = id;
       this.vlrTotal = vlrTotal;
       this.vlrJuros = vlrJuros;
       this.vlrDesconto = vlrDesconto;
       this.vlrMulta = vlrMulta;
       this.dtInipagamento = dtInipagamento;
       this.dtFimPagamento = dtFimPagamento;
       this.dtRegistro = dtRegistro;
       this.numParcela = numParcela;
       this.vlrPago = vlrPago;
       this.dtParcela = dtParcela;
       this.comissaos = comissaos;
    }
   
    public PagamentoVendaId getId() {
        return this.id;
    }
    
    public void setId(PagamentoVendaId id) {
        this.id = id;
    }
    public BigDecimal getVlrTotal() {
        return this.vlrTotal;
    }
    
    public void setVlrTotal(BigDecimal vlrTotal) {
        this.vlrTotal = vlrTotal;
    }
    public BigDecimal getVlrJuros() {
        return this.vlrJuros;
    }
    
    public void setVlrJuros(BigDecimal vlrJuros) {
        this.vlrJuros = vlrJuros;
    }
    public BigDecimal getVlrDesconto() {
        return this.vlrDesconto;
    }
    
    public void setVlrDesconto(BigDecimal vlrDesconto) {
        this.vlrDesconto = vlrDesconto;
    }
    public BigDecimal getVlrMulta() {
        return this.vlrMulta;
    }
    
    public void setVlrMulta(BigDecimal vlrMulta) {
        this.vlrMulta = vlrMulta;
    }
    public Date getDtInipagamento() {
        return this.dtInipagamento;
    }
    
    public void setDtInipagamento(Date dtInipagamento) {
        this.dtInipagamento = dtInipagamento;
    }
    public Date getDtFimPagamento() {
        return this.dtFimPagamento;
    }
    
    public void setDtFimPagamento(Date dtFimPagamento) {
        this.dtFimPagamento = dtFimPagamento;
    }
    public Date getDtRegistro() {
        return this.dtRegistro;
    }
    
    public void setDtRegistro(Date dtRegistro) {
        this.dtRegistro = dtRegistro;
    }
    public Integer getNumParcela() {
        return this.numParcela;
    }
    
    public void setNumParcela(Integer numParcela) {
        this.numParcela = numParcela;
    }
    public BigDecimal getVlrPago() {
        return this.vlrPago;
    }
    
    public void setVlrPago(BigDecimal vlrPago) {
        this.vlrPago = vlrPago;
    }
    public Date getDtParcela() {
        return this.dtParcela;
    }
    
    public void setDtParcela(Date dtParcela) {
        this.dtParcela = dtParcela;
    }
    public Set getComissaos() {
        return this.comissaos;
    }
    
    public void setComissaos(Set comissaos) {
        this.comissaos = comissaos;
    }




}


