package com.proj;
// Generated 19/06/2014 22:10:45 by Hibernate Tools 3.2.1.GA



/**
 * PagamentoVendaId generated by hbm2java
 */
public class PagamentoVendaId  implements java.io.Serializable {


     private int codContrato;
     private int seqPagamento;

    public PagamentoVendaId() {
    }

    public PagamentoVendaId(int codContrato, int seqPagamento) {
       this.codContrato = codContrato;
       this.seqPagamento = seqPagamento;
    }
   
    public int getCodContrato() {
        return this.codContrato;
    }
    
    public void setCodContrato(int codContrato) {
        this.codContrato = codContrato;
    }
    public int getSeqPagamento() {
        return this.seqPagamento;
    }
    
    public void setSeqPagamento(int seqPagamento) {
        this.seqPagamento = seqPagamento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PagamentoVendaId) ) return false;
		 PagamentoVendaId castOther = ( PagamentoVendaId ) other; 
         
		 return (this.getCodContrato()==castOther.getCodContrato())
 && (this.getSeqPagamento()==castOther.getSeqPagamento());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodContrato();
         result = 37 * result + this.getSeqPagamento();
         return result;
   }   


}


