package com.proj;
// Generated 19/06/2014 22:10:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int codUsuario;
     private String login;
     private String senha;
     private String flgStatus;
     private String ipAcessopadrao;
     private Set funcionarios = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int codUsuario, String login, String senha, String flgStatus, String ipAcessopadrao) {
        this.codUsuario = codUsuario;
        this.login = login;
        this.senha = senha;
        this.flgStatus = flgStatus;
        this.ipAcessopadrao = ipAcessopadrao;
    }
    public Usuario(int codUsuario, String login, String senha, String flgStatus, String ipAcessopadrao, Set funcionarios) {
       this.codUsuario = codUsuario;
       this.login = login;
       this.senha = senha;
       this.flgStatus = flgStatus;
       this.ipAcessopadrao = ipAcessopadrao;
       this.funcionarios = funcionarios;
    }
   
    public int getCodUsuario() {
        return this.codUsuario;
    }
    
    public void setCodUsuario(int codUsuario) {
        this.codUsuario = codUsuario;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getFlgStatus() {
        return this.flgStatus;
    }
    
    public void setFlgStatus(String flgStatus) {
        this.flgStatus = flgStatus;
    }
    public String getIpAcessopadrao() {
        return this.ipAcessopadrao;
    }
    
    public void setIpAcessopadrao(String ipAcessopadrao) {
        this.ipAcessopadrao = ipAcessopadrao;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }




}


