package com.proj;
// Generated 19/06/2014 22:10:45 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * VeiculoVenda generated by hbm2java
 */
public class VeiculoVenda  implements java.io.Serializable {


     private int codVeiculo;
     private Veiculo veiculo;
     private BigDecimal vlrVeiculo;
     private Set vendas = new HashSet(0);

    public VeiculoVenda() {
    }

	
    public VeiculoVenda(int codVeiculo, Veiculo veiculo) {
        this.codVeiculo = codVeiculo;
        this.veiculo = veiculo;
    }
    public VeiculoVenda(int codVeiculo, Veiculo veiculo, BigDecimal vlrVeiculo, Set vendas) {
       this.codVeiculo = codVeiculo;
       this.veiculo = veiculo;
       this.vlrVeiculo = vlrVeiculo;
       this.vendas = vendas;
    }
   
    public int getCodVeiculo() {
        return this.codVeiculo;
    }
    
    public void setCodVeiculo(int codVeiculo) {
        this.codVeiculo = codVeiculo;
    }
    public Veiculo getVeiculo() {
        return this.veiculo;
    }
    
    public void setVeiculo(Veiculo veiculo) {
        this.veiculo = veiculo;
    }
    public BigDecimal getVlrVeiculo() {
        return this.vlrVeiculo;
    }
    
    public void setVlrVeiculo(BigDecimal vlrVeiculo) {
        this.vlrVeiculo = vlrVeiculo;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


