package com.proj;
// Generated 19/06/2014 22:10:45 by Hibernate Tools 3.2.1.GA



/**
 * VendaId generated by hbm2java
 */
public class VendaId  implements java.io.Serializable {


     private int codVeiculo;
     private int seqVenda;

    public VendaId() {
    }

    public VendaId(int codVeiculo, int seqVenda) {
       this.codVeiculo = codVeiculo;
       this.seqVenda = seqVenda;
    }
   
    public int getCodVeiculo() {
        return this.codVeiculo;
    }
    
    public void setCodVeiculo(int codVeiculo) {
        this.codVeiculo = codVeiculo;
    }
    public int getSeqVenda() {
        return this.seqVenda;
    }
    
    public void setSeqVenda(int seqVenda) {
        this.seqVenda = seqVenda;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VendaId) ) return false;
		 VendaId castOther = ( VendaId ) other; 
         
		 return (this.getCodVeiculo()==castOther.getCodVeiculo())
 && (this.getSeqVenda()==castOther.getSeqVenda());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodVeiculo();
         result = 37 * result + this.getSeqVenda();
         return result;
   }   


}


