package com.proj;
// Generated 19/06/2014 22:10:45 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private VendaId id;
     private Cliente cliente;
     private VeiculoVenda veiculoVenda;
     private CondicaoPagamento condicaoPagamento;
     private Funcionario funcionario;
     private BigDecimal vlrVendido;
     private Date dtVenda;
     private Integer codContrato;
     private BigDecimal vlrDesconto;

    public Venda() {
    }

	
    public Venda(VendaId id, Cliente cliente, VeiculoVenda veiculoVenda, CondicaoPagamento condicaoPagamento, Funcionario funcionario, BigDecimal vlrVendido, Date dtVenda) {
        this.id = id;
        this.cliente = cliente;
        this.veiculoVenda = veiculoVenda;
        this.condicaoPagamento = condicaoPagamento;
        this.funcionario = funcionario;
        this.vlrVendido = vlrVendido;
        this.dtVenda = dtVenda;
    }
    public Venda(VendaId id, Cliente cliente, VeiculoVenda veiculoVenda, CondicaoPagamento condicaoPagamento, Funcionario funcionario, BigDecimal vlrVendido, Date dtVenda, Integer codContrato, BigDecimal vlrDesconto) {
       this.id = id;
       this.cliente = cliente;
       this.veiculoVenda = veiculoVenda;
       this.condicaoPagamento = condicaoPagamento;
       this.funcionario = funcionario;
       this.vlrVendido = vlrVendido;
       this.dtVenda = dtVenda;
       this.codContrato = codContrato;
       this.vlrDesconto = vlrDesconto;
    }
   
    public VendaId getId() {
        return this.id;
    }
    
    public void setId(VendaId id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public VeiculoVenda getVeiculoVenda() {
        return this.veiculoVenda;
    }
    
    public void setVeiculoVenda(VeiculoVenda veiculoVenda) {
        this.veiculoVenda = veiculoVenda;
    }
    public CondicaoPagamento getCondicaoPagamento() {
        return this.condicaoPagamento;
    }
    
    public void setCondicaoPagamento(CondicaoPagamento condicaoPagamento) {
        this.condicaoPagamento = condicaoPagamento;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public BigDecimal getVlrVendido() {
        return this.vlrVendido;
    }
    
    public void setVlrVendido(BigDecimal vlrVendido) {
        this.vlrVendido = vlrVendido;
    }
    public Date getDtVenda() {
        return this.dtVenda;
    }
    
    public void setDtVenda(Date dtVenda) {
        this.dtVenda = dtVenda;
    }
    public Integer getCodContrato() {
        return this.codContrato;
    }
    
    public void setCodContrato(Integer codContrato) {
        this.codContrato = codContrato;
    }
    public BigDecimal getVlrDesconto() {
        return this.vlrDesconto;
    }
    
    public void setVlrDesconto(BigDecimal vlrDesconto) {
        this.vlrDesconto = vlrDesconto;
    }




}


